### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by yejy53** [divyakraman/AerialDiffusion#1]
Hello, thank you for your excellent work. Can you provide the corresponding environment configuration code?

**Comment by yejy53** [comment]
Can you give an environment-specific version number?

**Comment by divyakraman** [comment]
Hello,

I don't remember the exact environment specific version numbers that I used at the time of working on this project. I am currently using 0.27.2 version of diffusers and the code works in that. I had to remove lines of code pertaining to version checks from the pipeline.py files in the codebase when I updated my diffusers version. 

Thanks!
